// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjWq1qLLvU728EBMiOLN9vGthQHcRrFSo',
    appId: '1:1086224477649:web:d0d6432a571410e54984f0',
    messagingSenderId: '1086224477649',
    projectId: 'notes-app-sync-ff2f7',
    authDomain: 'notes-app-sync-ff2f7.firebaseapp.com',
    storageBucket: 'notes-app-sync-ff2f7.firebasestorage.app',
    measurementId: 'G-8P0X9J2CD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF-k9ph9UXjmCfpY09Z9ceKjAL52kOST4',
    appId: '1:1086224477649:android:33ab583b4b4c39ad4984f0',
    messagingSenderId: '1086224477649',
    projectId: 'notes-app-sync-ff2f7',
    storageBucket: 'notes-app-sync-ff2f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCp3vJzsqOujQlRg2SQHxGpF-1KJz1iS4',
    appId: '1:1086224477649:ios:019c0ea6828db50e4984f0',
    messagingSenderId: '1086224477649',
    projectId: 'notes-app-sync-ff2f7',
    storageBucket: 'notes-app-sync-ff2f7.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCp3vJzsqOujQlRg2SQHxGpF-1KJz1iS4',
    appId: '1:1086224477649:ios:019c0ea6828db50e4984f0',
    messagingSenderId: '1086224477649',
    projectId: 'notes-app-sync-ff2f7',
    storageBucket: 'notes-app-sync-ff2f7.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjWq1qLLvU728EBMiOLN9vGthQHcRrFSo',
    appId: '1:1086224477649:web:a53849dd37733eb14984f0',
    messagingSenderId: '1086224477649',
    projectId: 'notes-app-sync-ff2f7',
    authDomain: 'notes-app-sync-ff2f7.firebaseapp.com',
    storageBucket: 'notes-app-sync-ff2f7.firebasestorage.app',
    measurementId: 'G-ZSJ6K1C2GD',
  );
}
